apiVersion: v1
kind: Service
metadata:
  name: single-app-single-collector
  labels:
    app: single-app-single-collector
  namespace: opentelemetry-demo
spec:
  type: NodePort
  selector:
    app: single-app-single-collector
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
      
---

apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry-collector
  namespace: opentelemetry-demo
spec:
  type: ClusterIP
  selector:
    app: opentelemetry-collector
  ports:
    - name: otel-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317